#ifndef _ERESULTSCHECKING_H_
#define _ERESULTSCHECKING_H_

enum EResultsChecking {
    SUCCESSFUL_CHECKING = 100,
    USER_ERROR = 101,
    SYSTEM_ERROR = 102,
    COMPILATION_ERROR = 103,
    RUN_TIME_ERROR = 105,
    UNKNOWN_ERROR = 105
};

#endif // _ERESULTSCHECKING_H_
